name: redpoint
description: A rock climbing journal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Custom Dependencies
  drift: ^2.0.2                         # database plugin
  path: ^1.8.1
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.9          # sqlite binaries
  provider: ^6.0.3                      # state management
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Customer Dev Dependencies
  drift_dev: ^2.0.2
  build_runner: ^2.2.0                  # needed for drift code generation
  storage_inspector: ^0.2.3             # viewing local storage/drift database during testing
  drift_local_storage_inspector: ^0.3.0 # sql local storage inspector
  dart_date: ^1.1.1

flutter:
  uses-material-design: true
