name: redpoint
description: A rock climbing journal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # Custom Dependencies
  drift: ^2.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.9
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # Customer Dev Dependencies
  drift_dev: ^2.1.0
  build_runner: ^2.2.0
  storage_inspector: ^0.2.3
  drift_local_storage_inspector: ^0.3.0
  dart_date: ^1.1.1

flutter:
  uses-material-design: true
