name: Build APK

on: [workflow_dispatch]

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable' # or: 'beta', 'dev' or 'master'
         cache: true

      - name: Build APK
        run: flutter build apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: redpoint_dev.apk
          path: build/app/outputs/apk/release/app-release.apk
        
