name: Flutter Test/Format/Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable' # or: 'beta', 'dev' or 'master'
         cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Run tests
        run: flutter test
