name: Flutter Test/Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable' # or: 'beta', 'dev' or 'master'
         cache: true
      - run: flutter --version

      - run: sqlite3 --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
